In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import sklearn
from sklearn.utils import shuffle
# from sklearn.model_selection import train_test_split

%matplotlib inline

df = pd.read_csv("C:/Users/shahh/OneDrive/Desktop/Research Paper - KS/Final CSV/April/final_data.csv")
# df = df.drop(columns=['File Name','Number of cells','Cell Number'])
df = shuffle(df)
df

,Sr. 0,Temperature,File Name,Series,Parallel,Shading,Number of cells,Voltage (V),Current (I),I/V,Solar Panel,Cell Number,Shade Percentage,IsShade
17285,17286,30,10X1_0shadding,10,1,0,10,3.66,4.34,1.19,1830,6,0.00,0
37661,37662,35,10X1_5shadding,10,1,5,10,1.02,2.18,2.14,3972,2,50.00,1
50166,50167,35,5X2_7shadding,5,2,7,10,1.87,4.35,2.33,5323,7,70.00,1
28575,28576,30,4X2_0shadding,4,2,0,8,0.76,8.68,11.43,3011,4,0.00,0
82803,82804,45,5X2_3shadding,5,2,3,10,1.84,6.51,3.54,8789,4,30.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62494,62495,40,4X2_0shadding,4,2,0,8,1.55,8.65,5.58,6607,3,0.00,0
61627,61628,40,3X3_6shadding,3,3,6,9,0.08,8.68,108.56,6508,8,66.67,0
64847,64848,40,5X2_10shadding,5,2,10,10,0.48,4.34,9.05,6892,8,100.00,1
90153,90154,50,10X1_8shadding,10,1,8,10,0.34,2.17,6.39,9524,4,80.00,1
62207,62208,40,3X3_9shadding,3,3,9,9,0.48,6.51,13.57,6573,3,100.00,1

In [2]:
df = df.drop(columns=['File Name'])
df

,Sr. 0,Temperature,Series,Parallel,Shading,Number of cells,Voltage (V),Current (I),I/V,Solar Panel,Cell Number,Shade Percentage,IsShade
17285,17286,30,10,1,0,10,3.66,4.34,1.19,1830,6,0.00,0
37661,37662,35,10,1,5,10,1.02,2.18,2.14,3972,2,50.00,1
50166,50167,35,5,2,7,10,1.87,4.35,2.33,5323,7,70.00,1
28575,28576,30,4,2,0,8,0.76,8.68,11.43,3011,4,0.00,0
82803,82804,45,5,2,3,10,1.84,6.51,3.54,8789,4,30.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62494,62495,40,4,2,0,8,1.55,8.65,5.58,6607,3,0.00,0
61627,61628,40,3,3,6,9,0.08,8.68,108.56,6508,8,66.67,0
64847,64848,40,5,2,10,10,0.48,4.34,9.05,6892,8,100.00,1
90153,90154,50,10,1,8,10,0.34,2.17,6.39,9524,4,80.00,1
62207,62208,40,3,3,9,9,0.48,6.51,13.57,6573,3,100.00,1

In [3]:
X = df.drop('IsShade', axis=1)
y = df['IsShade']

In [4]:

from sklearn.model_selection import train_test_split
# implementing train-test-split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.34, random_state=44)

In [7]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import roc_auc_score
from sklearn import metrics

In [6]:
# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=50,
                         learning_rate=1)
# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

In [8]:
print('Train set')
train_pred = model.predict_proba(X_train)
print('Adaboost Classifier roc-auc: {}'.format(roc_auc_score(y_train, train_pred[:,1])))
print('Test set')
test_pred = model.predict_proba(X_test)
print('Adaboost Classifier roc-auc: {}'.format(roc_auc_score(y_test, test_pred[:,1])))

Train set
Adaboost Classifier roc-auc: 1.0
Test set
Adaboost Classifier roc-auc: 1.0

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

nbc_cv_score = cross_val_score(model, X, y, cv=10, scoring='roc_auc')

In [13]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, y_pred))
print('\n')
print("=== All AUC Scores ===")
print(nbc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Adaboost: ", nbc_cv_score.mean())

=== Confusion Matrix ===
[[17153     0]
 [    0 17385]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17153
           1       1.00      1.00      1.00     17385

    accuracy                           1.00     34538
   macro avg       1.00      1.00      1.00     34538
weighted avg       1.00      1.00      1.00     34538



=== All AUC Scores ===
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


=== Mean AUC Score ===
Mean AUC Score - Adaboost:  1.0

In [12]:
from sklearn.metrics import accuracy_score

print("Train Accuracy :: ", accuracy_score(y_train, model.predict(X_train)))
print("Test Accuracy  :: ", accuracy_score(y_test, y_pred))

Train Accuracy ::  1.0
Test Accuracy  ::  1.0

In [13]:
from sklearn.model_selection import KFold
scores_rf = []
kfold = KFold(n_splits=10)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(nbc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(nbc, X, y, cv=kfold)))
print()
print("10 fold (KFold): ",np.mean(scores_rf))

Cross-validation scores:
None
Cross-validation scores:
[0.84042134 0.84701713 0.84573735 0.84839535 0.8529238  0.8429809
 0.84357157 0.8429809  0.84770624 0.85046269]

10 fold (KFold):  0.8462197282929711

In [12]:
from sklearn.model_selection import StratifiedKFold
scores_rf = []
skfold = StratifiedKFold(n_splits=10)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(nbc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(nbc, X, y, cv=skfold)))
print()
print("10 fold (StratiedFold): ",np.mean(scores_rf))

Cross-validation scores:
None
Cross-validation scores:
[0.84063392 0.84673688 0.8456541  0.84841028 0.85282536 0.84229179
 0.84404844 0.84267008 0.84729743 0.8512356 ]

10 fold (StratiedFold):  0.8462197282929711