In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import sklearn
from sklearn.utils import shuffle
# from sklearn.model_selection import train_test_split

%matplotlib inline

df = pd.read_csv("C:/Users/shahh/OneDrive/Desktop/Research Paper - KS/Final CSV/April/final_data.csv")
df = df.drop(columns=['File Name'])
df = shuffle(df)
df

,Sr. 0,Temperature,Series,Parallel,Shading,Number of cells,Voltage (V),Current (I),I/V,Solar Panel,Cell Number,Shade Percentage,IsShade
41420,41421,35,2,4,1,8,0.81,15.14,18.69,4353,1,12.5,1
28685,28686,30,4,2,0,8,1.86,8.44,4.54,3025,2,0.0,0
22336,22337,30,10,1,8,10,0.17,2.18,12.80,2335,7,80.0,1
33428,33429,30,5,2,8,10,0.69,4.35,6.30,3548,9,80.0,0
91396,91397,50,1,10,10,10,0.17,21.71,127.72,9648,7,100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92834,92835,50,2,4,7,8,0.75,8.64,11.52,9815,3,87.5,1
28557,28558,30,4,2,0,8,0.58,8.68,14.97,3009,2,0.0,0
42136,42137,35,2,4,7,8,0.77,8.66,11.25,4442,5,87.5,1
45400,45401,35,3,3,9,9,1.61,-0.91,-0.56,4792,8,100.0,1
54902,54903,40,10,1,5,10,4.23,2.18,0.52,5797,3,50.0,1

In [2]:
X = df.drop('IsShade', axis=1)
y = df['IsShade']

from sklearn.model_selection import train_test_split
# implementing train-test-split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.34, random_state=66)

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [4]:
dtc_predict = dtc.predict(X_test)

In [5]:
dtc_predict

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [6]:
from sklearn.metrics import roc_auc_score
print('Train set')
train_pred = dtc.predict_proba(X_train)
print('Decision Trees: {}'.format(roc_auc_score(y_train, train_pred[:,1])))
print('Test set')
test_pred = dtc.predict_proba(X_test)
print('Decision Trees: {}'.format(roc_auc_score(y_test, test_pred[:,1])))

Train set
Decision Trees: 1.0
Test set
Decision Trees: 1.0

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [8]:
dtc_cv_score = cross_val_score(dtc, X, y, cv=10, scoring='roc_auc')

In [10]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, dtc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, dtc_predict))
print('\n')
print("=== All AUC Scores ===")
print(dtc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", dtc_cv_score.mean())

=== Confusion Matrix ===
[[17172     0]
 [    0 17366]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17172
           1       1.00      1.00      1.00     17366

    accuracy                           1.00     34538
   macro avg       1.00      1.00      1.00     34538
weighted avg       1.00      1.00      1.00     34538



=== All AUC Scores ===
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  1.0

In [12]:
from sklearn.metrics import accuracy_score

print("Train Accuracy :: ", accuracy_score(y_train, dtc.predict(X_train)))
print("Test Accuracy  :: ", accuracy_score(y_test, dtc_predict))

Train Accuracy ::  1.0
Test Accuracy  ::  1.0