In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import sklearn
from sklearn.utils import shuffle

import math
from sklearn import svm
import sklearn.metrics as metric

# from sklearn.model_selection import train_test_split

%matplotlib inline

df = pd.read_csv("C:/Users/shahh/OneDrive/Desktop/Research Paper - KS/Final CSV/April/final_data.csv")
# df = df.drop(columns=['File Name','Number of cells','Cell Number'])
df = shuffle(df)
df

,Sr. 0,Temperature,File Name,Series,Parallel,Shading,Number of cells,Voltage (V),Current (I),I/V,Solar Panel,Cell Number,Shade Percentage,IsShade
36503,36504,35,10X1_3shadding,10,1,3,10,1.44,2.19,1.52,3856,4,30.0,0
85679,85680,50,10X1_10shadding,10,1,10,10,3.60,2.16,0.60,9076,10,100.0,1
5013,5014,27,10X1_7_Shadding.txt,10,1,7,10,2.14,2.18,1.02,502,4,70.0,1
81018,81019,45,4X2_7shadding,4,2,7,8,0.79,4.34,5.50,8600,7,87.5,1
34300,34301,35,10X1_0shadding,10,1,0,10,3.41,4.34,1.27,3636,1,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3146,3147,27,10X1_4_Shadding.txt,10,1,4,10,1.47,2.19,1.49,315,7,40.0,0
79610,79611,45,4X2_1shadding,4,2,1,8,1.11,6.52,5.87,8424,7,12.5,0
39699,39700,35,10X1_8shadding,10,1,8,10,3.40,2.17,0.64,4175,10,80.0,0
51828,51829,40,10X1_10shadding,10,1,10,10,3.49,2.17,0.62,5489,9,100.0,1
60489,60490,40,2X5_9shadding,2,5,9,10,0.70,10.84,15.49,6382,10,90.0,0

In [2]:
df = df.drop(columns=['File Name'])
df

,Sr. 0,Temperature,Series,Parallel,Shading,Number of cells,Voltage (V),Current (I),I/V,Solar Panel,Cell Number,Shade Percentage,IsShade
36503,36504,35,10,1,3,10,1.44,2.19,1.52,3856,4,30.0,0
85679,85680,50,10,1,10,10,3.60,2.16,0.60,9076,10,100.0,1
5013,5014,27,10,1,7,10,2.14,2.18,1.02,502,4,70.0,1
81018,81019,45,4,2,7,8,0.79,4.34,5.50,8600,7,87.5,1
34300,34301,35,10,1,0,10,3.41,4.34,1.27,3636,1,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3146,3147,27,10,1,4,10,1.47,2.19,1.49,315,7,40.0,0
79610,79611,45,4,2,1,8,1.11,6.52,5.87,8424,7,12.5,0
39699,39700,35,10,1,8,10,3.40,2.17,0.64,4175,10,80.0,0
51828,51829,40,10,1,10,10,3.49,2.17,0.62,5489,9,100.0,1
60489,60490,40,2,5,9,10,0.70,10.84,15.49,6382,10,90.0,0

In [3]:
X = df.drop('IsShade', axis=1)
y = df['IsShade']

In [4]:

from sklearn.model_selection import train_test_split
# implementing train-test-split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.34, random_state=44)

In [ ]:
svc = svm.SVC(kernel='linear').fit(X_train,y_train)
svc

In [10]:
from sklearn import svm

svm_classifier = svm.SVC(kernel='linear')
svm_classifier.fit(X_train,y_train)
svm_classifier_predict = svm_classifier.predict(X_test)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

rfc_cv_score = cross_val_score(svm_classifier, X, y, cv=10, scoring='roc_auc')

In [ ]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, svm_classifier_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, svm_classifier_predict))
print('\n')
print("=== All AUC Scores ===")
# print(rfc_cv_score)
# print('\n')
# print("=== Mean AUC Score ===")
# print("Mean AUC Score - Random Forest: ", rfc_cv_score.mean())

In [ ]:
from sklearn.metrics import accuracy_score

print("Train Accuracy :: ", accuracy_score(y_train, svm_classifier.predict(X_train)))
print("Test Accuracy  :: ", accuracy_score(y_test, svm_classifier_predict))

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

rfc_cv_score = cross_val_score(rfc, X, y, cv=10, scoring='roc_auc')

In [ ]:
from sklearn.model_selection import KFold
scores_rf = []
kfold = KFold(n_splits=3)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=kfold)))
print(np.mean(scores_rf))

In [ ]:
from sklearn.model_selection import KFold
scores_rf = []
kfold = KFold(n_splits=10)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=kfold)))
print(np.mean(scores_rf))

In [ ]:
from sklearn.model_selection import StratifiedKFold
scores_rf = []
skfold = StratifiedKFold(n_splits=3)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=skfold)))
print(np.mean(scores_rf))

In [ ]:
from sklearn.model_selection import StratifiedKFold
scores_rf = []
skfold = StratifiedKFold(n_splits=10)
print("Cross-validation scores:\n{}".format(
      scores_rf.append(cross_val_score(rfc, X, y, cv=kfold))))
print("Cross-validation scores:\n{}".format(
      cross_val_score(rfc, X, y, cv=skfold)))
print(np.mean(scores_rf))